# Generated by Django 3.2.3 on 2021-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pic',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to='static/media/ads/images/', width_field=400),
        ),
    ]
