# Generated by Django 3.2.3 on 2021-10-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='pic',
        ),
        migrations.AddField(
            model_name='ad',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the field', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
