# Generated by Django 3.2.3 on 2022-01-19 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0006_auto_20211125_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='comments',
            field=models.ManyToManyField(related_name='ad_comments_owned', through='ads.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
