# Generated by Django 3.2.3 on 2021-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ticker', models.TextField()),
                ('currency', models.TextField()),
                ('price', models.FloatField()),
                ('change', models.FloatField()),
                ('changepercent', models.FloatField()),
                ('peratio', models.FloatField()),
                ('dividend', models.FloatField()),
                ('eps', models.FloatField()),
                ('divyield', models.FloatField()),
                ('lower_52', models.FloatField()),
                ('upper_52', models.FloatField()),
            ],
        ),
    ]
