# Generated by Django 3.2.3 on 2021-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='change',
            field=models.FloatField(verbose_name='Veränderung'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='changepercent',
            field=models.FloatField(verbose_name='Veränderung in Prozent'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='currency',
            field=models.TextField(verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='dividend',
            field=models.FloatField(verbose_name='Dividende'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='divyield',
            field=models.FloatField(verbose_name='Dividendenrendite'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='eps',
            field=models.FloatField(verbose_name='Gewinn je Aktie'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='lower_52',
            field=models.FloatField(verbose_name='52-Wochen-Tief'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='peratio',
            field=models.FloatField(verbose_name='Kurs-Gewinn-Verhältnis'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='price',
            field=models.FloatField(verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='ticker',
            field=models.TextField(verbose_name='Tickersymbol'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='upper_52',
            field=models.FloatField(verbose_name='52-Wochen-Hoch'),
        ),
    ]
