# Generated by Django 3.2.3 on 2021-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0002_auto_20210603_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='currency',
            field=models.CharField(max_length=200, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='ticker',
            field=models.CharField(max_length=200, verbose_name='Tickersymbol'),
        ),
    ]
