# Generated by Django 3.2.3 on 2021-06-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0003_auto_20210603_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keydata',
            name='currency',
        ),
        migrations.AddField(
            model_name='keydata',
            name='currency_symbol',
            field=models.CharField(default='NA', max_length=200, verbose_name='Währung internationales Kürzel'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='shortrate',
            field=models.FloatField(blank=True, null=True, verbose_name='Shortquote'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rate', models.FloatField(verbose_name='aktuelle Rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproject.keydata')),
            ],
        ),
    ]
