# Generated by Django 3.2.3 on 2021-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0004_auto_20210605_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=100, verbose_name='internationales Kürzel'),
        ),
    ]
