# Generated by Django 3.2.3 on 2021-06-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0006_currency_keydata_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='keydata_entry',
        ),
        migrations.AlterField(
            model_name='keydata',
            name='currency_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataproject.currency'),
        ),
    ]
