# Generated by Django 3.2.3 on 2021-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0007_auto_20210608_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='currency_symbol',
            field=models.CharField(default='NA', max_length=200, verbose_name='Währung internationales Kürzel'),
        ),
    ]
