# Generated by Django 3.2.3 on 2021-06-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0011_auto_20210617_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectored',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproject.sector'),
        ),
        migrations.AlterField(
            model_name='sectored',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproject.keydata'),
        ),
    ]
