# Generated by Django 3.2.3 on 2021-06-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0012_auto_20210617_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectored',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='sectored',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='keydata',
            name='sectors',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Sectored',
        ),
    ]
