# Generated by Django 3.2.3 on 2021-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0014_newentrywatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydata',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
