# Generated by Django 3.2.3 on 2021-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0015_keydata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='ticker',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ticker'),
        ),
    ]
