# Generated by Django 3.2.3 on 2021-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0016_alter_newentrywatchlist_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='ticker',
            field=models.CharField(max_length=200, verbose_name='Ticker'),
        ),
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
