# Generated by Django 3.2.3 on 2021-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0017_auto_20210715_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currencysybol'),
        ),
    ]
