# Generated by Django 3.2.3 on 2021-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0019_auto_20210830_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydata',
            name='beta',
            field=models.FloatField(blank=True, null=True, verbose_name='Beta-Faktor'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='exdivdate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ex-Div-Datum'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='lower_day',
            field=models.FloatField(blank=True, null=True, verbose_name='Tages-Tief'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='publicfloat',
            field=models.FloatField(blank=True, null=True, verbose_name='Aktien handelbar in Mio'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='revperemployee',
            field=models.FloatField(blank=True, null=True, verbose_name='Umsatz pro MA in Tsd'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='sharesoutstanding',
            field=models.FloatField(blank=True, null=True, verbose_name='Aktien in Mio'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='upper_day',
            field=models.FloatField(blank=True, null=True, verbose_name='Tages-Hoch'),
        ),
    ]
