# Generated by Django 3.2.3 on 2021-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0020_auto_20210831_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currencysymbol'),
        ),
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='ticker',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ticker'),
        ),
    ]
