# Generated by Django 2.2.7 on 2021-09-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0022_keydata_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='changepercent',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Veränderung in Prozent'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
