# Generated by Django 2.2.7 on 2021-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0024_auto_20210914_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='change',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Veränderung'),
        ),
    ]
