# Generated by Django 2.2.7 on 2021-09-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0027_keydata_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydata',
            name='subsector',
            field=models.CharField(blank=True, choices=[('E', 'Energy'), ('M', 'Materials'), ('C', 'Commodities'), ('I', 'Industrials'), ('U', 'Utilities'), ('H', 'Healthcare'), ('F', 'Financials'), ('CD', 'Consumer Discretionary'), ('CS', 'Consumer Staples'), ('IT', 'Information Technology'), ('CServ', 'Communication Services'), ('RE', 'Real Estate')], max_length=10, null=True, verbose_name='Subsektor oder 2. Prio'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='sector',
            field=models.CharField(blank=True, choices=[('E', 'Energy'), ('M', 'Materials'), ('C', 'Commodities'), ('I', 'Industrials'), ('U', 'Utilities'), ('H', 'Healthcare'), ('F', 'Financials'), ('CD', 'Consumer Discretionary'), ('CS', 'Consumer Staples'), ('IT', 'Information Technology'), ('CServ', 'Communication Services'), ('RE', 'Real Estate')], max_length=10, null=True, verbose_name='Sektor'),
        ),
    ]
