# Generated by Django 3.2.3 on 2021-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0028_auto_20210915_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydata',
            name='cf',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Cash Flow'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='divepsrate',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Auszahlungsquote Div per Gewinn je Aktie'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='divfcfrate',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Div/FCF-Rate'),
        ),
        migrations.AddField(
            model_name='keydata',
            name='fcf',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Free Cash Flow'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
