# Generated by Django 2.2.7 on 2021-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0029_auto_20210916_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydata',
            name='dt_string',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Datum und Zeit'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newentrywatchlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
