# Generated by Django 2.2.7 on 2021-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0031_auto_20210924_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
    ]
