# Generated by Django 3.2.3 on 2022-01-28 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmalladVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Title must be greater than 2 characters')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallad_votes_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallad_votes_users', to=settings.AUTH_USER_MODEL)),
                ('userDownVotes', models.ManyToManyField(blank=True, related_name='smalladDownVotes', to=settings.AUTH_USER_MODEL)),
                ('userUpVotes', models.ManyToManyField(blank=True, related_name='smalladUpVotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kleinanzeige-Vote',
                'verbose_name_plural': 'Kleinanzeigen-Votes',
            },
        ),
    ]
