# Generated by Django 3.2.3 on 2022-01-23 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smallads', '0003_rename_owner_smalladcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smalladfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallad_favs_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
