# Generated by Django 3.2.3 on 2022-02-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallads', '0005_smallad_smallad_fav_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallad',
            name='smallad_fav_sum',
        ),
    ]
