# Generated by Django 3.2.3 on 2021-12-06 19:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
                ('poem1', models.TextField(blank=True, null=True)),
                ('poem2', models.TextField(blank=True, null=True)),
                ('poem3', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artist_images', verbose_name='Image')),
                ('altattr', models.CharField(blank=True, default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'), max_length=200, null=True, verbose_name='Alt Attribut')),
                ('description', models.TextField(blank=True, default=models.CharField(blank=True, default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'), max_length=200, null=True, verbose_name='Alt Attribut'), max_length=500, null=True)),
                ('artist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('text', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to=None)),
                ('price', models.FloatField()),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
