# Generated by Django 3.2.3 on 2021-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_remove_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='profpic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profpic', verbose_name='Profile Pic'),
        ),
    ]
