# Generated by Django 3.2.3 on 2021-12-07 14:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('artist', '0004_images_profpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='profpic',
        ),
        migrations.AddField(
            model_name='artist',
            name='profpic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profpic', verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_articles'),
        ),
        migrations.CreateModel(
            name='ArtistFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('artist', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArtistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_comments',
            field=models.ManyToManyField(related_name='artist_comments_owned', through='artist.ArtistComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_favorites',
            field=models.ManyToManyField(related_name='artist_favorite_artists', through='artist.ArtistFav', to=settings.AUTH_USER_MODEL),
        ),
    ]
