# Generated by Django 3.2.3 on 2021-12-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20211207_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_altattr',
            field=models.CharField(blank=True, default=models.CharField(max_length=200, verbose_name='Name'), max_length=200, null=True, verbose_name='Alt Attribut'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image_description',
            field=models.TextField(blank=True, default=models.CharField(blank=True, default=models.CharField(max_length=200, verbose_name='Name'), max_length=200, null=True, verbose_name='Alt Attribut'), max_length=500, null=True),
        ),
    ]
