# Generated by Django 3.2.3 on 2021-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_auto_20211208_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images', verbose_name='Image'),
        ),
    ]
