# Generated by Django 3.2.3 on 2021-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20211208_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images', verbose_name='Image 3'),
        ),
    ]
