# Generated by Django 3.2.3 on 2021-12-15 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0009_auto_20211215_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
