# Generated by Django 3.2.3 on 2021-09-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_latest_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='opened',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
