# Generated by Django 3.2.3 on 2021-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('currency', models.CharField(max_length=100, verbose_name='internationales Kürzel')),
                ('rate', models.FloatField(verbose_name='aktuelle Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Keydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Name')),
                ('ticker', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Tickersymbol')),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currencysymbol')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Preis')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='Veränderung')),
                ('changepercent', models.FloatField(blank=True, null=True, verbose_name='Veränderung in Prozent')),
                ('lower_day', models.FloatField(blank=True, null=True, verbose_name='Tages-Tief')),
                ('upper_day', models.FloatField(blank=True, null=True, verbose_name='Tages-Hoch')),
                ('sharesoutstanding', models.FloatField(blank=True, null=True, verbose_name='Aktien in Mio')),
                ('publicfloat', models.FloatField(blank=True, null=True, verbose_name='Aktien handelbar in Mio')),
                ('beta', models.FloatField(blank=True, null=True, verbose_name='Beta-Faktor')),
                ('revperemployee', models.FloatField(blank=True, null=True, verbose_name='Umsatz pro MA in Tsd')),
                ('peratio', models.FloatField(blank=True, null=True, verbose_name='Kurs-Gewinn-Verhältnis')),
                ('dividend', models.FloatField(blank=True, null=True, verbose_name='Dividende')),
                ('eps', models.FloatField(blank=True, null=True, verbose_name='Gewinn je Aktie')),
                ('divyield', models.FloatField(blank=True, null=True, verbose_name='Dividendenrendite')),
                ('exdivdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ex-Div-Datum')),
                ('shortrate', models.FloatField(blank=True, null=True, verbose_name='Shortquote')),
                ('lower_52', models.FloatField(blank=True, null=True, verbose_name='52-Wochen-Tief')),
                ('upper_52', models.FloatField(blank=True, null=True, verbose_name='52-Wochen-Hoch')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bemerkung')),
            ],
        ),
        migrations.CreateModel(
            name='NewEntryWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ticker', models.CharField(max_length=200, unique=True, verbose_name='Ticker')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
    ]
